title: Jekyll Theme
author: GitHub User
email: mitran@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello Git world.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cminimal
